# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 209c836928c9e581e560d15c834fb6fe24d23a7fe1c81f368e431fdcb8bc8ff309b30e19e77ba85fbb407861c06bd23dabad22e40c00ff78747a42c48ee49603

test:
  secret_key_base: e8535f5980d2e41f10148581eb71891676c0dc2482b95fabd3954b9ee5ac583be1ee3c394d6cc2e5af78b686a947b8c3cf2524ca40dc4d02b1092f419458d922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
